### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by runvnc** [EddieOne/open-source-tiny-home#2]
Hello, thanks so much for putting this up on github.  I though other tiny housers might be interested so I posted it on http://reddit.com/r/tinyhouses in case you want to comment.

**Comment by retlehs** [comment]
found this repo via @runvnc, thanks for sharing it

very cool idea @EddieOne

**Comment by EddieOne** [comment]
Hi guys, Thank you for the support! Every open source creator dreams of having a project grow beyond what one person could do alone. It's great to see people thinking open source and valuing contributions that can enrich communities on a global scale.
